
export const corporateGallery = [
    "/corporate/1.jpg",
    "/corporate/12.jpg",
    "/corporate/3.jpg",
    "/corporate/4.jpg",
    "/corporate/5.jpg",
    "/corporate/6.jpg",
    "/corporate/7.jpg",
    "/corporate/8.jpg",
    "/corporate/9.jpg",
    "/corporate/10.jpg",
    "/corporate/11.jpg",
    "/corporate/12.jpg",
    "/corporate/13.jpg",
    "/corporate/14.jpg",
    "/corporate/15.jpg",
    "/corporate/16.jpg",
    "/corporate/17.jpg",
    "/corporate/18.jpg",
    "/corporate/19.jpg",
    "/corporate/20.jpg",
    "/corporate/21.jpg",
    "/corporate/22.jpg",
    "/corporate/23.jpg",
];
